"""Report generator — produces auditable PDFs from synthesizer output.

The PDF is what the compliance team hands to auditors or regulators. Format
is intentionally austere: no marketing language, plain regulatory-style
prose, deterministic structure.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)


_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ARCA SENTRY — Compliance Audit Report</title>
<style>
  @page {{ size: A4; margin: 2cm; }}
  body {{ font-family: 'Georgia', 'Times New Roman', serif; font-size: 10.5pt;
          line-height: 1.5; color: #222; }}
  h1 {{ font-size: 20pt; color: #6b5520; border-bottom: 3px solid #c9a227;
        padding-bottom: 6px; margin-top: 0; }}
  h2 {{ font-size: 13pt; color: #6b5520; margin-top: 20pt;
        border-bottom: 1px solid #d4b54a; padding-bottom: 3px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 10pt 0;
           font-size: 9.5pt; }}
  th {{ background: #c9a227; color: white; text-align: left;
        padding: 5pt 7pt; }}
  td {{ border-bottom: 1px solid #e5d4a0; padding: 5pt 7pt;
        vertical-align: top; }}
  .meta {{ background: #fbf6e6; padding: 8pt 12pt; border-left: 4px solid #c9a227;
           margin: 12pt 0; }}
  .verdict-critical {{ color: #b00020; font-weight: bold; }}
  .verdict-warning {{ color: #c98a00; font-weight: bold; }}
  .verdict-advisory {{ color: #406b20; }}
  pre {{ background: #f6f6f6; padding: 8pt; border-radius: 3pt;
         font-size: 9pt; white-space: pre-wrap; word-wrap: break-word; }}
  footer {{ margin-top: 30pt; font-size: 8.5pt; color: #888; text-align: center;
            border-top: 1px solid #ddd; padding-top: 8pt; }}
</style>
</head>
<body>

<h1>ARCA SENTRY — Compliance Audit Report</h1>

<div class="meta">
  <strong>Interaction ID:</strong> {interaction_id}<br>
  <strong>Issued at:</strong> {issued_at}<br>
  <strong>Severity:</strong> <span class="verdict-{severity}">{severity_upper}</span><br>
  <strong>Action taken:</strong> {action_taken}
</div>

<h2>1. Executive summary</h2>
<p>{short}</p>

<h2>2. Detailed analysis</h2>
{long_html}

<h2>3. Findings</h2>
<table>
  <thead>
    <tr><th>Agent</th><th>Regulation</th><th>Article</th><th>Confidence</th><th>Rationale</th></tr>
  </thead>
  <tbody>
    {findings_rows}
  </tbody>
</table>

<h2>4. Interaction transcript</h2>
<p><strong>User request</strong></p>
<pre>{request}</pre>
<p><strong>AI response</strong></p>
<pre>{response}</pre>

<h2>5. Provenance</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  <tr><td>Channel</td><td>{channel}</td></tr>
  <tr><td>Actor</td><td>{actor}</td></tr>
  <tr><td>Synthesizer model</td><td>{synth_model}</td></tr>
  <tr><td>Tokens (prompt / completion)</td><td>{tokens}</td></tr>
  <tr><td>Event store hash</td><td>{event_hash}</td></tr>
</table>

<footer>
  Generated by ARCA SENTRY · B Drive IT · {issued_at}<br>
  This report is reproducible from the append-only event store via interaction ID.
</footer>

</body>
</html>"""


def render_report(
    *,
    interaction_id: str,
    channel: str,
    actor: str,
    request: str,
    response: str,
    severity: str,
    action_taken: str,
    short: str,
    long: str,
    findings: list[dict[str, Any]],
    synth_model: str,
    tokens_prompt: str,
    tokens_completion: str,
    event_hash: str = "",
) -> str:
    """Render the HTML report. PDF rendering is done by `render_pdf`."""
    long_html = "\n".join(f"<p>{p}</p>" for p in long.split("\n\n") if p.strip())
    findings_rows = "\n".join(
        "<tr><td>{a}</td><td>{r}</td><td>{art}</td><td>{c:.2f}</td><td>{rat}</td></tr>".format(
            a=f.get("agent_name", ""),
            r=f.get("regulation", ""),
            art=f.get("article") or "—",
            c=float(f.get("confidence", 0.0)),
            rat=_escape(f.get("rationale", "")),
        )
        for f in findings
    )

    return _HTML_TEMPLATE.format(
        interaction_id=interaction_id,
        issued_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        severity=severity,
        severity_upper=severity.upper(),
        action_taken=action_taken,
        short=_escape(short),
        long_html=long_html,
        findings_rows=findings_rows,
        request=_escape(request),
        response=_escape(response),
        channel=channel,
        actor=actor,
        synth_model=synth_model,
        tokens=f"{tokens_prompt} / {tokens_completion}",
        event_hash=event_hash or "(not provided)",
    )


def render_pdf(html: str, out_path: str | Path) -> Path:
    """Write the report to disk as PDF."""
    try:
        from weasyprint import HTML
    except ImportError as exc:
        raise RuntimeError(
            "weasyprint not installed; install with `pip install weasyprint`"
        ) from exc

    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    HTML(string=html).write_pdf(target=str(path))
    return path


def _escape(s: str) -> str:
    return (
        s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
         .replace('"', "&quot;").replace("'", "&#39;")
    )
